version: 2

sources:
  - name: raw
    database: DB_BI
    schema: raw
    tables:
      - name: usuario
      - name: solicitud_portabilidad
      - name: portabilidad_exitosa
      - name: accion_cliente