name: CI-CD dbt AzureSQL

on:
  push:
    branches: [ main ]

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar ODBC Driver 17 para SQL Server
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y curl gnupg unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17

      - name: Instalar dependencias
        run: pip install dbt-sqlserver

      - name: Crear profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          bi_dbt:
            outputs:
              dev:
                type: sqlserver
                driver: 'ODBC Driver 17 for SQL Server'
                host: "${{ secrets.DBT_HOST }}"
                port: 1433
                user: "${{ secrets.DBT_USER }}"
                password: "${{ secrets.DBT_PASSWORD }}"
                database: "${{ secrets.DBT_DATABASE }}"
                schema: "${{ secrets.DBT_SCHEMA }}"
                threads: 1
                encrypt: true
                trust_cert: true
            target: dev
          EOF

      - name: Testear conexión con dbt debug
        run: dbt debug --profiles-dir ~/.dbt
